include:
  - docker-compose.base.yml


services:
  backend:
    build:
      context: ./backend
      args:
        - SERVER__HOST=localhost
        - SERVER__PORT=8000
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - ./backend/alembic:/app/alembic
    networks:
      - backend-network
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    networks:
      - backend-network
    restart: unless-stopped
    environment:
      - NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
      - NODE_ENV=development


volumes:
  redis_data:
