include:
  - docker-compose.base.yml


services:
  backend:
    build:
      context: ./backend
      args:
        - SERVER__HOST=localhost
        - SERVER__PORT=8000
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - ./backend/alembic:/app/alembic
    networks:
      - backend-network


volumes:
  redis_data:
